import { db } from '@/server/db';
import { contentItems } from '@/server/db/schema';
import { and, isNotNull, desc } from 'drizzle-orm';

export async function GET(): Promise<Response> {
  const podcasts = await db.query.contentItems.findMany({
    where: and(isNotNull(contentItems.podcastUrl)),
    orderBy: [desc(contentItems.publishedAt)],
    limit: 50,
    columns: {
      id: true, title: true, authors: true, publishedAt: true,
      podcastUrl: true, podcastDuration: true, rawText: true, sourceUrl: true,
    },
  });

  const baseUrl   = process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000';
  const buildDate = new Date().toUTCString();

  const items = podcasts.map(p => {
    const pubDate  = p.publishedAt.toUTCString();
    const desc     = (p.rawText ?? '').slice(0, 500).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const author   = (p.authors ?? []).join(', ') || 'AI Pulse';
    const duration = p.podcastDuration ? `<itunes:duration>${p.podcastDuration}</itunes:duration>` : '';
    return `    <item>
      <title><![CDATA[${p.title}]]></title>
      <link>${p.sourceUrl}</link>
      <description><![CDATA[${desc}]]></description>
      <author>${author}</author>
      <pubDate>${pubDate}</pubDate>
      <guid isPermaLink="false">${p.id}</guid>
      <enclosure url="${p.podcastUrl}" type="audio/mpeg" />
      <itunes:title><![CDATA[${p.title}]]></itunes:title>
      ${duration}
    </item>`;
  }).join('\n');

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>AI Pulse Podcasts</title>
    <link>${baseUrl}</link>
    <description>AI and ML research papers as audio podcasts, generated by AI Pulse.</description>
    <language>en-us</language>
    <lastBuildDate>${buildDate}</lastBuildDate>
    <itunes:author>AI Pulse</itunes:author>
    <itunes:category text="Technology" />
${items}
  </channel>
</rss>`;

  return new Response(rss, {
    status: 200,
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
